# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
workspace 'project'

target 'SchoolDiary' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
#  supports_swift_versions '< 5.0'
  # Pods for SchoolDiary
    pod 'Disk', '~> 0.6.3'
    pod 'TinyConstraints'
end
